# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json
# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html
app.default:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app.social:
    resource:
        path: ../src/Controller/Social
        namespace: App\Controller\Social
    prefix: /social
    type: attribute

app.security:
    resource:
        path: ../src/Controller/Security
        namespace: App\Controller\Security
    type: attribute

app.personal_space:
    resource:
        path: ../src/Controller/PersonalSpace
        namespace: App\Controller\PersonalSpace
    prefix: /espace-perso
    type: attribute

app.comments:
    resource:
        path: ../src/Controller/Comment
        namespace: App\Controller\Comment
    prefix: /commentaire
    type: attribute

app.private:
    resource:
        path: ../src/Controller/Fragments
        namespace: App\Controller\Fragments
    type: attribute

#La location est définie à partir d'ici
app.location:
    resource:
        path: ../src/Controller/Location
        namespace: App\Controller\Location
    prefix: /{location}
    type: attribute
